"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 12:07:18.493479
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('area', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('tz', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('evaluation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario', sa.String(length=60), nullable=False),
    sa.Column('policies', sa.JSON(), nullable=False),
    sa.Column('seeds', sa.JSON(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=False),
    sa.Column('champion', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('scenario',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('sim_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('sim_s', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sim_event', schema=None) as batch_op:
        batch_op.create_index('ix_sim_event_world_seq', ['world_id', 'seq'], unique=False)

    op.create_table('training_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cafe_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('commission', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cafe_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('cat', sa.String(length=20), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('staple', sa.Boolean(), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.create_index('ix_menu_item_sku', ['cafe_id', 'sku'], unique=True)

    op.create_table('world',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cafe_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('scenario', sa.String(length=60), nullable=False),
    sa.Column('policy', sa.String(length=4), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('counterfactual',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('catalog_key', sa.String(length=40), nullable=False),
    sa.Column('seeds', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counterfactual', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counterfactual_world_id'), ['world_id'], unique=False)

    op.create_table('daily_kpi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_kpi', schema=None) as batch_op:
        batch_op.create_index('ix_daily_kpi_world_day', ['world_id', 'day'], unique=True)
        batch_op.create_index(batch_op.f('ix_daily_kpi_world_id'), ['world_id'], unique=False)

    op.create_table('disruption',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('target', sa.String(length=40), nullable=True),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disruption', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disruption_world_id'), ['world_id'], unique=False)

    op.create_table('investment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('catalog_key', sa.String(length=40), nullable=False),
    sa.Column('effect', sa.JSON(), nullable=False),
    sa.Column('sim_s', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_world_id'), ['world_id'], unique=False)

    op.create_table('menu_intervention',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('sim_s', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_intervention', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_intervention_world_id'), ['world_id'], unique=False)

    op.create_table('order',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('persona', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('party_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('placed_s', sa.Float(), nullable=False),
    sa.Column('promised_s', sa.Float(), nullable=False),
    sa.Column('ready_s', sa.Float(), nullable=True),
    sa.Column('served_s', sa.Float(), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment', sa.String(length=20), nullable=True),
    sa.Column('reject_reason', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_world_id'), ['world_id'], unique=False)
        batch_op.create_index('ix_order_world_no', ['world_id', 'order_no'], unique=True)

    op.create_table('policy_decision',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('policy', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('top_factors', sa.JSON(), nullable=False),
    sa.Column('sim_s', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_decision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_decision_world_id'), ['world_id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('old', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('new', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('by', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('sim_s', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_world_id'), ['world_id'], unique=False)

    op.create_table('review',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.String(length=36), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('causes', sa.JSON(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('persona', sa.String(length=20), nullable=False),
    sa.Column('sim_s', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_world_id'), ['world_id'], unique=False)

    op.create_table('order_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('mods', sa.JSON(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_item_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_world_id'), ['world_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_item_world_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_order_id'))

    op.drop_table('order_item')
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_world_id'))

    op.drop_table('review')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_world_id'))

    op.drop_table('price_history')
    with op.batch_alter_table('policy_decision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_decision_world_id'))

    op.drop_table('policy_decision')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index('ix_order_world_no')
        batch_op.drop_index(batch_op.f('ix_order_world_id'))

    op.drop_table('order')
    with op.batch_alter_table('menu_intervention', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_intervention_world_id'))

    op.drop_table('menu_intervention')
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_world_id'))

    op.drop_table('investment')
    with op.batch_alter_table('disruption', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disruption_world_id'))

    op.drop_table('disruption')
    with op.batch_alter_table('daily_kpi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_kpi_world_id'))
        batch_op.drop_index('ix_daily_kpi_world_day')

    op.drop_table('daily_kpi')
    with op.batch_alter_table('counterfactual', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counterfactual_world_id'))

    op.drop_table('counterfactual')
    op.drop_table('world')
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_index('ix_menu_item_sku')

    op.drop_table('menu_item')
    op.drop_table('channel')
    op.drop_table('training_run')
    with op.batch_alter_table('sim_event', schema=None) as batch_op:
        batch_op.drop_index('ix_sim_event_world_seq')

    op.drop_table('sim_event')
    op.drop_table('scenario')
    op.drop_table('policy')
    op.drop_table('model_registry')
    op.drop_table('evaluation')
    op.drop_table('cafe')
    # ### end Alembic commands ###
